"""Send the ski search results summary by email via SMTP."""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import markdown as md


# ── HTML template ────────────────────────────────────────────────────────────

_HTML_WRAPPER = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  /* Reset */
  body, p, h1, h2, h3, h4, ul, ol, li, table, td, th {{
    margin: 0; padding: 0; box-sizing: border-box;
  }}

  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
    background: #f0f4f8;
    color: #1a202c;
    line-height: 1.6;
  }}

  .wrapper {{
    max-width: 720px;
    margin: 32px auto;
    background: #ffffff;
    border-radius: 12px;
    overflow: hidden;
    box-shadow: 0 4px 24px rgba(0,0,0,0.10);
  }}

  /* Header */
  .header {{
    background: linear-gradient(135deg, #1e3a5f 0%, #2d6a9f 100%);
    padding: 36px 40px 28px;
    text-align: center;
  }}
  .header .logo {{
    font-size: 28px;
    font-weight: 700;
    color: #ffffff;
    letter-spacing: 1px;
  }}
  .header .logo span {{
    color: #7ec8e3;
  }}
  .header .tagline {{
    font-size: 14px;
    color: #a8d4ec;
    margin-top: 4px;
    letter-spacing: 0.5px;
  }}

  /* Meta cards */
  .meta {{
    display: flex;
    flex-wrap: wrap;
    gap: 0;
    background: #f7fafc;
    border-bottom: 1px solid #e2e8f0;
  }}
  .meta-item {{
    flex: 1 1 160px;
    padding: 16px 24px;
    border-right: 1px solid #e2e8f0;
  }}
  .meta-item:last-child {{ border-right: none; }}
  .meta-label {{
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.8px;
    color: #718096;
    font-weight: 600;
    margin-bottom: 4px;
  }}
  .meta-value {{
    font-size: 15px;
    font-weight: 700;
    color: #1a202c;
  }}

  /* Body */
  .body {{
    padding: 32px 40px;
  }}

  h1 {{ font-size: 24px; color: #1e3a5f; margin: 0 0 20px; }}
  h2 {{
    font-size: 18px; color: #1e3a5f;
    margin: 32px 0 12px;
    padding-bottom: 6px;
    border-bottom: 2px solid #bee3f8;
  }}
  h3 {{ font-size: 15px; color: #2d6a9f; margin: 24px 0 8px; font-weight: 700; }}

  p {{ margin: 0 0 14px; font-size: 15px; color: #2d3748; }}

  ul, ol {{ margin: 0 0 14px 20px; }}
  li {{ margin-bottom: 6px; font-size: 15px; color: #2d3748; }}
  li p {{ margin: 0; }}

  strong {{ color: #1a202c; }}
  em {{ color: #718096; }}

  a {{ color: #2d6a9f; text-decoration: none; font-weight: 600; }}
  a:hover {{ text-decoration: underline; }}

  hr {{
    border: none;
    border-top: 1px solid #e2e8f0;
    margin: 28px 0;
  }}

  /* Tables (fallback ranking) */
  table {{
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
    margin: 16px 0 24px;
  }}
  th {{
    background: #1e3a5f;
    color: #ffffff;
    padding: 10px 12px;
    text-align: left;
    font-weight: 600;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }}
  td {{
    padding: 9px 12px;
    border-bottom: 1px solid #e2e8f0;
    color: #2d3748;
    vertical-align: top;
  }}
  tr:nth-child(even) td {{ background: #f7fafc; }}
  tr:hover td {{ background: #ebf8ff; }}

  blockquote {{
    border-left: 3px solid #bee3f8;
    margin: 0 0 14px;
    padding: 8px 16px;
    color: #4a5568;
    background: #f7fafc;
    border-radius: 0 4px 4px 0;
  }}

  /* Footer */
  .footer {{
    background: #f7fafc;
    border-top: 1px solid #e2e8f0;
    padding: 20px 40px;
    text-align: center;
    font-size: 12px;
    color: #a0aec0;
  }}
  .footer a {{ color: #718096; font-weight: normal; }}
</style>
</head>
<body>
<div class="wrapper">

  <div class="header">
    <div class="logo">⛷ Ski<span>Master</span></div>
    <div class="tagline">Automated Group Ski Accommodation Search</div>
  </div>

  <div class="meta">
    {meta_items}
  </div>

  <div class="body">
    {body_html}
  </div>

  <div class="footer">
    Generated by SkiMaster &nbsp;·&nbsp; {resorts_searched} resorts searched
    &nbsp;·&nbsp; <a href="https://github.com/lamyiowce/skimaster">github.com/lamyiowce/skimaster</a>
  </div>

</div>
</body>
</html>
"""

_META_ITEM = """\
    <div class="meta-item">
      <div class="meta-label">{label}</div>
      <div class="meta-value">{value}</div>
    </div>"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _meta_item(label: str, value: str) -> str:
    return _META_ITEM.format(label=label, value=value)


def _extract_meta(markdown_text: str) -> dict:
    """Pull the key-value pairs from the metadata block at the top of results.md."""
    meta = {}
    for line in markdown_text.splitlines():
        for key, pattern in [
            ("dates",    "**Dates:**"),
            ("group",    "**Group size:**"),
            ("budget",   "**Budget:**"),
            ("walk",     "**Max walk to lift:**"),
            ("analyzed", "**Properties analyzed:**"),
            ("searched", "**Search date:**"),
        ]:
            if pattern in line:
                meta[key] = line.split(pattern, 1)[1].strip()
    return meta


def _strip_meta_block(markdown_text: str) -> str:
    """Remove the top metadata block (up to and including the first ---) from the markdown."""
    lines = markdown_text.splitlines()
    # Find the first "---" separator
    for i, line in enumerate(lines):
        if line.strip() == "---":
            return "\n".join(lines[i + 1:]).lstrip()
    return markdown_text


def _strip_footer(markdown_text: str) -> str:
    """Remove the trailing --- and footer line."""
    lines = markdown_text.splitlines()
    # Find the last "---" separator
    for i in range(len(lines) - 1, -1, -1):
        if lines[i].strip() == "---":
            return "\n".join(lines[:i]).rstrip()
    return markdown_text


def _markdown_to_html(text: str) -> str:
    return md.markdown(
        text,
        extensions=["tables", "nl2br"],
        output_format="html",
    )


def _build_html(markdown_text: str) -> str:
    meta = _extract_meta(markdown_text)

    meta_items = "\n".join([
        _meta_item("Dates",              meta.get("dates", "—")),
        _meta_item("Group size",         meta.get("group", "—")),
        _meta_item("Budget",             meta.get("budget", "—")),
        _meta_item("Walk to lift",       meta.get("walk", "—")),
        _meta_item("Properties checked", meta.get("analyzed", "—")),
    ])

    # Strip metadata block and footer from the body before rendering
    body_md = _strip_footer(_strip_meta_block(markdown_text))
    body_html = _markdown_to_html(body_md)

    import re as _re
    resorts_match = _re.search(r"(\d+) resorts searched", markdown_text)
    resorts_searched = resorts_match.group(1) if resorts_match else "?"

    return _HTML_WRAPPER.format(
        meta_items=meta_items,
        body_html=body_html,
        resorts_searched=resorts_searched,
    )


# ── Public API ────────────────────────────────────────────────────────────────

def send_summary_email(results_md_path: str) -> None:
    """Send the contents of results_md_path to EMAIL_TO via SMTP.

    Required environment variables:
        EMAIL_TO        Recipient address (or comma-separated list)
        SMTP_HOST       SMTP server hostname (e.g. smtp.gmail.com)
        SMTP_USER       SMTP login / sender address
        SMTP_PASSWORD   SMTP password or app-password

    Optional:
        SMTP_PORT       Defaults to 587 (STARTTLS)
    """
    recipient = os.environ.get("EMAIL_TO", "")
    smtp_host = os.environ.get("SMTP_HOST", "")
    smtp_user = os.environ.get("SMTP_USER", "")
    smtp_password = os.environ.get("SMTP_PASSWORD", "")
    smtp_port = int(os.environ.get("SMTP_PORT", "587"))

    if not all([recipient, smtp_host, smtp_user, smtp_password]):
        missing = [
            name
            for name, val in {
                "EMAIL_TO": recipient,
                "SMTP_HOST": smtp_host,
                "SMTP_USER": smtp_user,
                "SMTP_PASSWORD": smtp_password,
            }.items()
            if not val
        ]
        print(f"Email not sent — missing env vars: {', '.join(missing)}")
        return

    try:
        with open(results_md_path) as f:
            markdown_text = f.read()
    except FileNotFoundError:
        print(f"Email not sent — results file not found: {results_md_path}")
        return

    html_body = _build_html(markdown_text)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = "⛷ SkiMaster — Ski Accommodation Search Results"
    msg["From"] = smtp_user
    msg["To"] = recipient
    msg.attach(MIMEText(markdown_text, "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    print(f"Sending results email to {recipient} via {smtp_host}:{smtp_port}...")
    with smtplib.SMTP(smtp_host, smtp_port) as smtp:
        smtp.ehlo()
        smtp.starttls()
        smtp.login(smtp_user, smtp_password)
        smtp.send_message(msg)
    print("Email sent successfully.")
